### ISSUE TITLE
[question] better to use doc_values rather than field_data on low memory installs

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#29] opened 2014-12-05 12:52 UTC
worth re-reading:
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/geo-memory.html
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/doc-values.html

**Comment by missinglink** [comment] 2015-07-07 15:00
this is helpful for installing in low memory environments such as the raspberry pi, this ticket can be easily resolved by documenting this in a README or wiki

**Comment by dianashk** [comment] 2016-04-21 16:32
Closing as duplicate of #50

**Closed by dianashk** 2016-04-21 16:32 UTC
Labels: low hanging fruit
